apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers # Required. Kafka broker connection setting
      value:  kafka.default.svc.cluster.local:9092
    - name: authType
      value: "none"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kvstore
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=postgresql.default.svc.cluster.local user=postgres password=postgres port=5432 connect_timeout=10 database=dapr"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deployment
spec:
  selector:
    matchLabels:
      app: sweets-shop
  template:
    metadata:
      labels:
        app: sweets-shop
        app.kubernetes.io/name: sweets-shop
        app.kubernetes.io/part-of: sweets-shop
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - name: sweets-shop
          image: shop:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: sweets-shop
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
